### ISSUE TITLE
Works of Art

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/basira#1]
### Overview

Works of Art are a key data model. They're the starting point for all data entry. They're at the top of the core data hierarchy, and relate to many of the other data types.

### To Do

- [ ] Database, based on field list provided; note both native fields and associated models. 
- [ ] Index view, with filter, basic search, column selector, actions including edit, delete, duplicate, view.
- [ ] Edit view should allow creation of nested & associated objects, at least as stubs, several levels deep.
- [ ] Select from searchable/autocomplete menus, some one to one, some one to many, some many to many, from value lists, configuration lists, and other core data models
- [ ] Image upload and attachment, should use an S3-compatible backend.
- [ ] Show view, maybe as a modal, to preview the finished record.
- [ ] Existing data and attached images to be migrated.
